#!/bin/bash
# Generate BuildConfig.swift in $DERIVED_FILE_DIR. Invoked from each
# Xcode-native target's pre-build phase. Reads identity values from
# the build environment (set by BuildConfig/Identity.xcconfig).
set -euo pipefail

: "${DERIVED_FILE_DIR:?must be set by Xcode}"
: "${XCMCPTAP_SERVICE_NAME:?missing from xcconfig - wire BuildConfig/Identity.xcconfig into the target configFiles}"
: "${XCMCPTAP_APP_DISPLAY_NAME:?missing from xcconfig}"
: "${XCMCPTAP_SYMLINK_NAME:?missing from xcconfig}"

mkdir -p "$DERIVED_FILE_DIR"

cat > "$DERIVED_FILE_DIR/BuildConfig.swift" <<EOF
// AUTO-GENERATED by scripts/gen-build-config.sh.
// Source of truth: BuildConfig/Identity.xcconfig. Regenerated on
// every Xcode build — never commit this file.
import XcodeMCPTapShared

enum BuildConfig {
  static let identity = Identity(
    serviceName: "$XCMCPTAP_SERVICE_NAME",
    appDisplayName: "$XCMCPTAP_APP_DISPLAY_NAME",
    symlinkName: "$XCMCPTAP_SYMLINK_NAME",
  )
}
EOF
